// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type VideoserviceChannel struct {
	ID          string
	TenantID    string
	Name        string
	Description sql.NullString
	CreatedBy   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type VideoserviceChannelMember struct {
	ID        string
	ChannelID string
	UserID    string
	Role      string
	AddedBy   string
	CreatedAt time.Time
}

type VideoserviceVideo struct {
	ID             string
	Title          string
	Description    string
	Url            string
	CreatedAt      time.Time
	UploadedUserID string
	UpdatedAt      time.Time
	IsPrivate      sql.NullBool
	TenantID       sql.NullString
	ChannelID      sql.NullString
	IsDeleted      sql.NullBool
	FileSizeBytes  sql.NullInt64
}
