// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addVideoToSpace = `-- name: AddVideoToSpace :exec
INSERT INTO video_spaces (
    video_id,
    space_id,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type AddVideoToSpaceParams struct {
	VideoID   string
	SpaceID   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) AddVideoToSpace(ctx context.Context, arg AddVideoToSpaceParams) error {
	_, err := q.db.ExecContext(ctx, addVideoToSpace,
		arg.VideoID,
		arg.SpaceID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSpace = `-- name: CreateSpace :exec

INSERT INTO spaces (
    id,
    name,
    description,
    user_id,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
`

type CreateSpaceParams struct {
	ID          string
	Name        string
	Description sql.NullString
	UserID      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// Space related queries
func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) error {
	_, err := q.db.ExecContext(ctx, createSpace,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createVideoUploaded = `-- name: CreateVideoUploaded :exec
INSERT INTO videos (
    id,
    title,
    description,
    url,
    uploaded_user_id,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3, 
    ?4,
    ?5,
    ?6,
    ?7
)
`

type CreateVideoUploadedParams struct {
	ID             string
	Title          string
	Description    string
	Url            string
	UploadedUserID string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) CreateVideoUploaded(ctx context.Context, arg CreateVideoUploadedParams) error {
	_, err := q.db.ExecContext(ctx, createVideoUploaded,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Url,
		arg.UploadedUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getAllVideoUploadedByUser = `-- name: GetAllVideoUploadedByUser :many
SELECT id, title, description, url, created_at, uploaded_user_id, updated_at FROM videos WHERE uploaded_user_id = ?1 ORDER BY created_at DESC
`

func (q *Queries) GetAllVideoUploadedByUser(ctx context.Context, id string) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getAllVideoUploadedByUser, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CreatedAt,
			&i.UploadedUserID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllVideoUploadedByUserPaginated = `-- name: GetAllVideoUploadedByUserPaginated :many
SELECT id, title, description, url, created_at, uploaded_user_id, updated_at FROM videos 
WHERE uploaded_user_id = ?1
ORDER BY created_at DESC
LIMIT ?3 OFFSET ?2
`

type GetAllVideoUploadedByUserPaginatedParams struct {
	UserID     string
	PageNumber int64
	PageSize   int64
}

func (q *Queries) GetAllVideoUploadedByUserPaginated(ctx context.Context, arg GetAllVideoUploadedByUserPaginatedParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getAllVideoUploadedByUserPaginated, arg.UserID, arg.PageNumber, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CreatedAt,
			&i.UploadedUserID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpaceByID = `-- name: GetSpaceByID :one
SELECT id, name, description, user_id, created_at, updated_at FROM spaces 
WHERE id = ?1 AND user_id = ?2
LIMIT 1
`

type GetSpaceByIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetSpaceByID(ctx context.Context, arg GetSpaceByIDParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpaceByID, arg.ID, arg.UserID)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpacesByUser = `-- name: GetSpacesByUser :many
SELECT id, name, description, user_id, created_at, updated_at FROM spaces 
WHERE user_id = ?1 
ORDER BY created_at DESC
`

func (q *Queries) GetSpacesByUser(ctx context.Context, userID string) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, getSpacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideoByID = `-- name: GetVideoByID :one
SELECT id, title, description, url, created_at, uploaded_user_id, updated_at FROM videos 
WHERE id = ?1 AND uploaded_user_id = ?2
LIMIT 1
`

type GetVideoByIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetVideoByID(ctx context.Context, arg GetVideoByIDParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideoByID, arg.ID, arg.UserID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Url,
		&i.CreatedAt,
		&i.UploadedUserID,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideosInSpace = `-- name: GetVideosInSpace :many
SELECT v.id, v.title, v.description, v.url, v.created_at, v.uploaded_user_id, v.updated_at FROM videos v
INNER JOIN video_spaces vs ON v.id = vs.video_id
WHERE vs.space_id = ?1 AND v.uploaded_user_id = ?2
ORDER BY v.created_at DESC
`

type GetVideosInSpaceParams struct {
	SpaceID string
	UserID  string
}

func (q *Queries) GetVideosInSpace(ctx context.Context, arg GetVideosInSpaceParams) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getVideosInSpace, arg.SpaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Url,
			&i.CreatedAt,
			&i.UploadedUserID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeVideoFromSpace = `-- name: RemoveVideoFromSpace :exec
DELETE FROM video_spaces 
WHERE video_id = ?1 AND space_id = ?2
`

type RemoveVideoFromSpaceParams struct {
	VideoID string
	SpaceID string
}

func (q *Queries) RemoveVideoFromSpace(ctx context.Context, arg RemoveVideoFromSpaceParams) error {
	_, err := q.db.ExecContext(ctx, removeVideoFromSpace, arg.VideoID, arg.SpaceID)
	return err
}
