# fly.toml app configuration file generated for sortedstream on 2025-06-06T05:07:26-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sortedstream'
primary_region = 'atl'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
  # Essential timeouts for large file uploads (15 minutes)
  connect_timeout = 900
  idle_timeout = 900

[[vm]]
  size = 'performance-1x'  # 1GB RAM to handle large uploads

[mounts]
  source = "sortedstream_data"
  destination = "/data"

[env]
VIDEOSERVICE_FILESTOREDIR = "/data/uploads"
VIDEOSERVICE_DB_URL = "/data/db.sqlite"

[scale]
  count = 1