// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID              string
	Content         string
	VideoID         string
	UserID          string
	ParentCommentID sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type CommentLike struct {
	ID        string
	UserID    string
	CommentID string
	CreatedAt time.Time
}
