// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Comment struct {
	ID        string
	Content   string
	VideoID   string
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
