// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CheckUserLikedComment(ctx context.Context, arg CheckUserLikedCommentParams) (int64, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) error
	DeleteComment(ctx context.Context, arg DeleteCommentParams) error
	GetAllCommentsByUserPaginated(ctx context.Context, arg GetAllCommentsByUserPaginatedParams) ([]Comment, error)
	GetComentsAndRepliesForVideoID(ctx context.Context, videoID string) ([]GetComentsAndRepliesForVideoIDRow, error)
	GetCommentByID(ctx context.Context, arg GetCommentByIDParams) (Comment, error)
	GetCommentCount(ctx context.Context, videoID string) (int64, error)
	GetCommentLikesCount(ctx context.Context, commentID string) (int64, error)
	GetCommentsByVideo(ctx context.Context, videoID string) ([]Comment, error)
	GetCommentsByVideoPaginated(ctx context.Context, arg GetCommentsByVideoPaginatedParams) ([]Comment, error)
	GetRepliesByCommentID(ctx context.Context, commentID sql.NullString) ([]Comment, error)
	LikeComment(ctx context.Context, arg LikeCommentParams) error
	UnlikeComment(ctx context.Context, arg UnlikeCommentParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) error
	test(ctx context.Context) ([]Comment, error)
}

var _ Querier = (*Queries)(nil)
