// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type User struct {
	ID        string
	Username  string
	Email     string
	AvatarUrl string
	CreatedAt time.Time
}
