// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO userservice_users (
    id,
    username,
    email,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
) RETURNING id, username, email, created_at
`

type CreateUserParams struct {
	ID        string
	Username  string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UserserviceUser, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.CreatedAt,
	)
	var i UserserviceUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, created_at FROM userservice_users 
WHERE email = ?1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (UserserviceUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i UserserviceUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
