// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addUserCount = `-- name: AddUserCount :exec
UPDATE userservice_user_limits 
SET users_count = users_count + ?, last_calculated_at = ?, updated_at = ?
WHERE user_id = ?
`

type AddUserCountParams struct {
	UsersCount       sql.NullInt64
	LastCalculatedAt sql.NullInt64
	UpdatedAt        int64
	UserID           string
}

func (q *Queries) AddUserCount(ctx context.Context, arg AddUserCountParams) error {
	_, err := q.db.ExecContext(ctx, addUserCount,
		arg.UsersCount,
		arg.LastCalculatedAt,
		arg.UpdatedAt,
		arg.UserID,
	)
	return err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO userservice_tenants (
    id,
    name,
    description,
    is_personal,
    created_at,
    created_by
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
) RETURNING id, name, description, is_personal, created_at, created_by
`

type CreateTenantParams struct {
	ID          string
	Name        string
	Description sql.NullString
	IsPersonal  bool
	CreatedAt   time.Time
	CreatedBy   string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (UserserviceTenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPersonal,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	var i UserserviceTenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createTenantUser = `-- name: CreateTenantUser :one
INSERT INTO userservice_tenant_users (
    id,
    tenant_id,
    user_id,
    role,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
) RETURNING id, tenant_id, user_id, role, created_at
`

type CreateTenantUserParams struct {
	ID        string
	TenantID  string
	UserID    string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) CreateTenantUser(ctx context.Context, arg CreateTenantUserParams) (UserserviceTenantUser, error) {
	row := q.db.QueryRowContext(ctx, createTenantUser,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	var i UserserviceTenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO userservice_users (
    id,
    username,
    email,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
) RETURNING id, username, email, created_at
`

type CreateUserParams struct {
	ID        string
	Username  string
	Email     string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UserserviceUser, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.CreatedAt,
	)
	var i UserserviceUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const createUserLimits = `-- name: CreateUserLimits :one
INSERT INTO userservice_user_limits (
    user_id, users_count, last_calculated_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?)
RETURNING user_id, users_count, last_calculated_at, created_at, updated_at
`

type CreateUserLimitsParams struct {
	UserID           string
	UsersCount       sql.NullInt64
	LastCalculatedAt sql.NullInt64
	CreatedAt        int64
	UpdatedAt        int64
}

func (q *Queries) CreateUserLimits(ctx context.Context, arg CreateUserLimitsParams) (UserserviceUserLimit, error) {
	row := q.db.QueryRowContext(ctx, createUserLimits,
		arg.UserID,
		arg.UsersCount,
		arg.LastCalculatedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserserviceUserLimit
	err := row.Scan(
		&i.UserID,
		&i.UsersCount,
		&i.LastCalculatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, description, is_personal, created_at, created_by FROM userservice_tenants WHERE id = ?1
`

func (q *Queries) GetTenantByID(ctx context.Context, id string) (UserserviceTenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var i UserserviceTenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT id, name, description, is_personal, created_at, created_by FROM userservice_tenants 
WHERE name = ?1 AND created_by = ?2
`

type GetTenantByNameParams struct {
	Name      string
	CreatedBy string
}

// Tenant queries
func (q *Queries) GetTenantByName(ctx context.Context, arg GetTenantByNameParams) (UserserviceTenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByName, arg.Name, arg.CreatedBy)
	var i UserserviceTenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPersonal,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getTenantUsers = `-- name: GetTenantUsers :many
SELECT 
    tu.role, tu.created_at,
    u.id as user_id, u.username, u.email,
    t.created_at as tenant_created_at,
    t.name as tenant_name
FROM userservice_tenant_users tu
JOIN userservice_users u ON tu.user_id = u.id
JOIN userservice_tenants t ON tu.tenant_id = t.id
WHERE tu.tenant_id = ?1
ORDER BY tu.created_at ASC
`

type GetTenantUsersRow struct {
	Role            string
	CreatedAt       time.Time
	UserID          string
	Username        string
	Email           string
	TenantCreatedAt time.Time
	TenantName      string
}

func (q *Queries) GetTenantUsers(ctx context.Context, tenantID string) ([]GetTenantUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getTenantUsers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTenantUsersRow
	for rows.Next() {
		var i GetTenantUsersRow
		if err := rows.Scan(
			&i.Role,
			&i.CreatedAt,
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.TenantCreatedAt,
			&i.TenantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, created_at FROM userservice_users 
WHERE email = ?1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (UserserviceUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i UserserviceUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getUserLimits = `-- name: GetUserLimits :one
SELECT user_id, users_count, last_calculated_at, created_at, updated_at FROM userservice_user_limits WHERE user_id = ? LIMIT 1
`

// User limits queries (moved from payment service)
func (q *Queries) GetUserLimits(ctx context.Context, userID string) (UserserviceUserLimit, error) {
	row := q.db.QueryRowContext(ctx, getUserLimits, userID)
	var i UserserviceUserLimit
	err := row.Scan(
		&i.UserID,
		&i.UsersCount,
		&i.LastCalculatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoleInTenant = `-- name: GetUserRoleInTenant :one
SELECT role FROM userservice_tenant_users 
WHERE tenant_id = ?1 AND user_id = ?2
`

type GetUserRoleInTenantParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) GetUserRoleInTenant(ctx context.Context, arg GetUserRoleInTenantParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRoleInTenant, arg.TenantID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUserTenants = `-- name: GetUserTenants :many
SELECT 
    tu.id as tenant_user_id,
    t.id as tenant_id, 
    t.name, 
    t.description, 
    t.is_personal, 
    t.created_at, 
    t.created_by,
    tu.role, 
    tu.created_at as joined_at
FROM userservice_tenants t
JOIN userservice_tenant_users tu ON t.id = tu.tenant_id
WHERE tu.user_id = ?1
ORDER BY t.created_at DESC
`

type GetUserTenantsRow struct {
	TenantUserID string
	TenantID     string
	Name         string
	Description  sql.NullString
	IsPersonal   bool
	CreatedAt    time.Time
	CreatedBy    string
	Role         string
	JoinedAt     time.Time
}

func (q *Queries) GetUserTenants(ctx context.Context, userID string) ([]GetUserTenantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTenants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTenantsRow
	for rows.Next() {
		var i GetUserTenantsRow
		if err := rows.Scan(
			&i.TenantUserID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsPersonal,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserLimits = `-- name: UpsertUserLimits :exec
INSERT INTO userservice_user_limits (
    user_id, users_count, last_calculated_at, created_at, updated_at
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    users_count = excluded.users_count,
    last_calculated_at = excluded.last_calculated_at,
    updated_at = excluded.updated_at
`

type UpsertUserLimitsParams struct {
	UserID           string
	UsersCount       sql.NullInt64
	LastCalculatedAt sql.NullInt64
	CreatedAt        int64
	UpdatedAt        int64
}

func (q *Queries) UpsertUserLimits(ctx context.Context, arg UpsertUserLimitsParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserLimits,
		arg.UserID,
		arg.UsersCount,
		arg.LastCalculatedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
