# fly.toml app configuration file generated for sortedstream-internal on 2025-06-17T20:59:00-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sortedstream-internal'
primary_region = 'atl'

[env]
  VIDEOSERVICE_DB_URL = '/data/db.sqlite'
  VIDEOSERVICE_FILESTOREDIR = '/data/uploads'

[[mounts]]
  source = 'sortedstream_internal_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']


  # Essential timeouts for large file uploads (15 minutes)
  connect_timeout = 900
  idle_timeout = 900

[[vm]]
  size = 'performance-1x'


[scale]
  count = 1