name: Build Go Binary

on:
  push:
    tags:
      - build-v[0-9]+.[0-9]+.[0-9]+-rc*
    branches:
      - feature/deploy-into-fly
jobs:
  build:
    name: Build Go Binary with Embedded React Frontend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ENV_NAME: staging
    defaults:
      run:
        working-directory: ./frontend/webapp
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm build --mode ${{ env.ENV_NAME }}

      - name: Copy frontend dist to backend
        run: |
          cp -rf dist ../../backend/mono/webapp

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build Go binary
        working-directory: ./backend/mono
        # VERSION=$(git describe --tags)
        run: go build  -o stream-${{ env.ENV_NAME }}-binary

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/mono
          file: ../../deploy/Dockerfile
          tags: ghcr.io/sortedstartup/stream-${{ env.ENV_NAME }}:latest
          push: true
          args:
            ENV_NAME: ${{ env.ENV_NAME }}


