name: Web App Staging Build and Deploy

on:
  push:
    tags:
      - webapp-v[0-9]+.[0-9]+.[0-9]+-rc*

jobs:
  build-app:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./frontend/webapp
    permissions:
      contents: read
      deployments: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # Specify the Node.js version

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm build --mode staging

    - name: Deploy to sortedstory-staging.pages.dev
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_SORTEDSTARTUP_API_SECRET }}
        accountId: ${{ secrets.CLOUDFLARE_SORTEDSTARTUP_ACCOUNT_ID }}
        command: |
           pages deploy frontend/webapp/dist --project-name=sortedstory-staging --branch=main